### ISSUE TITLE
Missing file?

### ISSUE THREAD

**Issue by tomersagi** [parisni/UimaOnSpark#5]
The instructions specify we should use a **ref_doc_section.csv** file. Where is this file ? How do we create it?

**Comment by parisni** [comment]
Try with this kind of csv. If it does not work, I will dig in the source code

first col: unique id of the section
second: group id
third: content of the section

```
"1","1","Current plan:"
"2","2","Blood products:"
"3","2","Total In:"
"4","2","Balance:"
"5","2","Allergies:"
"6","2","Last dose of Antibiotics:"
"7","2","IVF:"
"8","2","Stool:"
"9","2","Drains:"
"10","2","Total out:"
"11","2","PO:"
"12","2","NG:"
"13","2","TF:"
"14","2","Urine:"
"15","2","Infusions:"
"16","2","RR:"
"17","2","HR:"
"18","2","BP:"
"19","2","ABG:"
```

**Comment by tomersagi** [comment]
This works fine. Thanks.
